
CREATE TABLE CARS
(
  UNIQUE_ID           VARCHAR(50) NOT NULL COMMENT '유니크_ID',
  COMPANY_CODE        VARCHAR(50) NOT NULL COMMENT '회사_코드',
  CARSNAME_CODE       VARCHAR(50) NOT NULL COMMENT '자동차 이름_ 코드',
  PRODUCTIONYEAR_CODE VARCHAR(50) NOT NULL COMMENT '연식_코드',
  CARS_OPTION_CODE_ID VARCHAR(50) NOT NULL COMMENT '자동차옵션_ID',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '자동차 브랜드';

CREATE TABLE CARS_OPTIONS 
(
  UNIQUE_ID           VARCHAR(50) NOT NULL COMMENT '유니크_ID',
  CARS_OPTION_CODE_ID VARCHAR(50) NOT NULL COMMENT '자동차옵션_ID',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '자동차 옵션';

CREATE TABLE CARS_OPTIONS_CODE
(
  Car_OPTION          VARCHAR(50) NOT NULL COMMENT '옵션',
  CARS_OPTION_CODE_ID VARCHAR(50) NOT NULL COMMENT '자동차옵션_ID',
  PRIMARY KEY (CARS_OPTION_CODE_ID)
) COMMENT '자동차 옵션 코드';

CREATE TABLE CARSNAME_CODE
(
  CARSNAME      VARCHAR(50) NOT NULL COMMENT '자동차 이름',
  CARSNAME_CODE VARCHAR(50) NOT NULL COMMENT '자동차 이름_ 코드',
  PRIMARY KEY (CARSNAME_CODE)
) COMMENT '자동차 이름 _코드';

CREATE TABLE COMPANY_CODE
(
  COMPANY      VARCHAR(50) NOT NULL COMMENT '회사이름',
  COMPANY_CODE VARCHAR(50) NOT NULL COMMENT '회사_코드',
  PRIMARY KEY (COMPANY_CODE)
) COMMENT '회사_코드';

CREATE TABLE PRODUCTIONYEAR_CODE
(
  PRODUCTIONYEAR      VARCHAR(50) NOT NULL COMMENT '연식',
  PRODUCTIONYEAR_CODE VARCHAR(50) NOT NULL COMMENT '연식_코드',
  PRIMARY KEY (PRODUCTIONYEAR_CODE)
) COMMENT '연식_코드';

ALTER TABLE CARS
  ADD CONSTRAINT FK_COMPANY_CODE_TO_CARS
    FOREIGN KEY (COMPANY_CODE)
    REFERENCES COMPANY_CODE (COMPANY_CODE);

ALTER TABLE CARS
  ADD CONSTRAINT FK_CARSNAME_CODE_TO_CARS
    FOREIGN KEY (CARSNAME_CODE)
    REFERENCES CARSNAME_CODE (CARSNAME_CODE);

ALTER TABLE CARS
  ADD CONSTRAINT FK_PRODUCTIONYEAR_CODE_TO_CARS
    FOREIGN KEY (PRODUCTIONYEAR_CODE)
    REFERENCES PRODUCTIONYEAR_CODE (PRODUCTIONYEAR_CODE);

ALTER TABLE CARS
  ADD CONSTRAINT FK_CARS_OPTIONS _TO_CARS
    FOREIGN KEY (CARS_OPTION_CODE_ID)
    REFERENCES CARS_OPTIONS  (UNIQUE_ID);

ALTER TABLE CARS_OPTIONS 
  ADD CONSTRAINT FK_CARS_OPTIONS_CODE_TO_CARS_OPTIONS 
    FOREIGN KEY (CARS_OPTION_CODE_ID)
    REFERENCES CARS_OPTIONS_CODE (CARS_OPTION_CODE_ID);
