
CREATE TABLE GENDER_CODE
(
  GENDER      VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_CODE VARCHAR(50) NOT NULL COMMENT '성별_코드',
  PRIMARY KEY (GENDER_CODE)
) COMMENT '성별_코드';

CREATE TABLE MAINTENANCE STRATEGIES _CODE
(
  MAINTENANCE STRATEGIES       VARCHAR(50) NOT NULL COMMENT ' 유지방안',
  MAINTENANCE STRATEGIES _CODE VARCHAR(50) NOT NULL COMMENT '유지방안_CODE',
  PRIMARY KEY (MAINTENANCE STRATEGIES _CODE)
) COMMENT '유지방안_CODE';

CREATE TABLE MEDICAL TEST RESULT_CODE
(
  MEDICAL TEST RESULT      VARCHAR(50) NOT NULL COMMENT '검진결과',
  MEDICAL TEST RESULT_CODE VARCHAR(50) NOT NULL COMMENT '검진결과_CODE',
  PRIMARY KEY (MEDICAL TEST RESULT_CODE)
) COMMENT '검진결과_CODE';

CREATE TABLE PATIONTS INFORMATION 
(
  NAME                         VARCHAR(50) NOT NULL COMMENT '이름',
  BLOODGLUCOSE                 INTEGER     NOT NULL COMMENT '혈당(mg/dL)',
  BLOODPRESSURE                INTEGER     NOT NULL COMMENT '혈압(mmHG)',
  AGE                          INTEGER     NOT NULL COMMENT '나이',
  HEIGHT                       INTEGER     NOT NULL COMMENT '키(cm)',
  BODYWEIGHT                   INTEGER     NOT NULL COMMENT '체중(kg)',
  GENDER_CODE                  VARCHAR(50) NOT NULL COMMENT '성별_코드',
  PATIONTS INFORMATION_ID      VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  MEDICAL TEST RESULT_CODE     VARCHAR(50) NOT NULL COMMENT '검진결과_코드 ',
  MAINTENANCE STRATEGIES _CODE VARCHAR(50) NOT NULL COMMENT '유지방안_코드',
  RETEST ITEMS_CODE            VARCHAR(50) NOT NULL COMMENT '재검진항목_코드',
  PRIMARY KEY (PATIONTS INFORMATION_ID)
) COMMENT '환자정보_';

CREATE TABLE RETEST ITEMS_CODE
(
  RETEST ITEMS      VARCHAR(50) NOT NULL COMMENT '재검진항목',
  RETEST ITEMS_CODE VARCHAR(50) NOT NULL COMMENT '재검진항목_코드 ',
  PRIMARY KEY (RETEST ITEMS_CODE)
) COMMENT '재검진항목_코드 ';

ALTER TABLE PATIONTS INFORMATION 
  ADD CONSTRAINT FK_GENDER_CODE_TO_PATIONTS INFORMATION 
    FOREIGN KEY (GENDER_CODE)
    REFERENCES GENDER_CODE (GENDER_CODE);

ALTER TABLE PATIONTS INFORMATION 
  ADD CONSTRAINT FK_RETEST ITEMS_CODE_TO_PATIONTS INFORMATION 
    FOREIGN KEY (MEDICAL TEST RESULT_CODE)
    REFERENCES RETEST ITEMS_CODE (RETEST ITEMS_CODE);

ALTER TABLE PATIONTS INFORMATION 
  ADD CONSTRAINT FK_MAINTENANCE STRATEGIES _CODE_TO_PATIONTS INFORMATION 
    FOREIGN KEY (MAINTENANCE STRATEGIES _CODE)
    REFERENCES MAINTENANCE STRATEGIES _CODE (MAINTENANCE STRATEGIES _CODE);

ALTER TABLE PATIONTS INFORMATION 
  ADD CONSTRAINT FK_MEDICAL TEST RESULT_CODE_TO_PATIONTS INFORMATION 
    FOREIGN KEY (RETEST ITEMS_CODE)
    REFERENCES MEDICAL TEST RESULT_CODE (MEDICAL TEST RESULT_CODE);
