CREATE TABLE GENDER_CODE
(
  GENDER      VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_CODE VARCHAR(50) NOT NULL COMMENT '성별_코드',
  PRIMARY KEY (GENDER_CODE)
) COMMENT '성별_코드';

CREATE TABLE MAINTENANCE_STRATEGIES_CODE
(
  MAINTENANCE_STRATEGIES       VARCHAR(50) NOT NULL COMMENT ' 유지방안',
  MAINTENANCE_STRATEGIES_CODE VARCHAR(50) NOT NULL COMMENT '유지방안_CODE',
  PRIMARY KEY (MAINTENANCE_STRATEGIES_CODE)
) COMMENT '유지방안_CODE';

CREATE TABLE MEDICAL_TEST_RESULT_CODE
(
  MEDICAL_TEST_RESULT      VARCHAR(50) NOT NULL COMMENT '검진결과',
  MEDICAL_TEST_RESULT_CODE VARCHAR(50) NOT NULL COMMENT '검진결과_코드 ',
  PRIMARY KEY (MEDICAL_TEST_RESULT_CODE)
) COMMENT '검진결과_코드 ';

CREATE TABLE RETEST_ITEMS_CODE
(
  RETEST_ITEMS      VARCHAR(50) NOT NULL COMMENT '재검진항목',
  RETEST_ITEMS_CODE VARCHAR(50) NOT NULL COMMENT '재검진항목_코드 ',
  PRIMARY KEY (RETEST_ITEMS_CODE)
) COMMENT '재검진항목_코드';

CREATE TABLE PATIONTS_INFORMATION 
(
  NAME                         VARCHAR(50) NOT NULL COMMENT '이름',
  BLOODGLUCOSE                 INTEGER     NOT NULL COMMENT '혈당(mg/dL)',
  BLOODPRESSURE                INTEGER     NOT NULL COMMENT '혈압(mmHG)',
  AGE                          INTEGER     NOT NULL COMMENT '나이',
  HEIGHT                       INTEGER     NOT NULL COMMENT '키(cm)',
  BODYWEIGHT                   INTEGER     NOT NULL COMMENT '체중(kg)',
  GENDER_CODE                  VARCHAR(50) NOT NULL COMMENT '성별_코드',
  PATIONTS_INFORMATION_ID      VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  MEDICAL_TEST_RESULT_CODE     VARCHAR(50) NOT NULL COMMENT '검진결과_코드 ',
  MAINTENANCE_STRATEGIES_CODE VARCHAR(50) NOT NULL COMMENT '유지방안_코드',
  RETEST_ITEMS_CODE            VARCHAR(50) NOT NULL COMMENT '재검진항_코드',
  PRIMARY KEY (PATIONTS_INFORMATION_ID)
) COMMENT '환자정보_';

ALTER TABLE PATIONTS_INFORMATION 
  ADD CONSTRAINT FK_GENDER_CODE_TO_PATIONTSINFORMATION 
    FOREIGN KEY (GENDER_CODE)
    REFERENCES GENDER_CODE (GENDER_CODE);

ALTER TABLE PATIONTS_INFORMATION 
  ADD CONSTRAINT FK_MEDICAL_TEST_RESULT_CODE_TO_PATIONTS_INFORMATION 
    FOREIGN KEY (MEDICAL_TEST_RESULT_CODE)
    REFERENCES MEDICAL_TEST_RESULT_CODE (MEDICAL_TEST_RESULT_CODE);

ALTER TABLE PATIONTS_INFORMATION 
  ADD CONSTRAINT FK_MAINTENANCESTRATEGIES_CODE_TO_PATIONTS_INFORMATION 
    FOREIGN KEY (MAINTENANCE_STRATEGIES_CODE)
    REFERENCES MAINTENANCE_STRATEGIES_CODE (MAINTENANCE_STRATEGIES_CODE);

ALTER TABLE PATIONTS_INFORMATION 
  ADD CONSTRAINT FK_MEDICAL_TEST_RESULT_CODE_TO_PATIONTS_INFORMATION 
    FOREIGN KEY (RETEST_ITEMS_CODE)
    REFERENCES MEDICAL_TEST_RESULT_CODE (MEDICAL_TEST_RESULT_CODE);
